In [1]:
!pip install --upgrade tables
!pip install eli5




     |████████████████████████████████| 4.3MB 2.8MB/s 
  Found existing installation: tables 3.4.4
    Uninstalling tables-3.4.4:
      Successfully uninstalled tables-3.4.4
     |████████████████████████████████| 112kB 2.8MB/s 


In [2]:
import pandas as pd
import numpy as np

from sklearn.dummy import DummyRegressor
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_error as mae
from sklearn.model_selection import cross_val_score

import eli5
from eli5.sklearn import PermutationImportance

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)
Using TensorFlow backend.


In [3]:
cd "/content/drive/My Drive/Colab Notebooks/dw_matrix/matrix_two"

/content/drive/My Drive/Colab Notebooks/dw_matrix/matrix_two


Wczytywanie danych

In [4]:
ls


dw_matrix_car/


In [5]:
cd dw_matrix_car/

/content/drive/My Drive/Colab Notebooks/dw_matrix/matrix_two/dw_matrix_car


In [0]:
df = pd.read_hdf('data/car.h5')

In [7]:
df.shape

(106494, 155)

In [8]:
df.columns

Index(['breadcrumb', 'created_at', 'price_currency', 'price_details',
       'price_value', 'seller_address', 'seller_name', 'seller_type',
       'feature_czujniki-parkowania-przednie',
       'feature_poduszka-powietrzna-chroniąca-kolana',
       ...
       'param_pearl', 'param_stan', 'param_wersja', 'param_emisja-co2',
       'param_body-type', 'param_matowy', 'param_bezwypadkowy',
       'param_akryl-(niemetalizowany)', 'param_monthly-payment-value',
       'car_id'],
      dtype='object', length=155)

Dummy model

In [9]:
df.select_dtypes(np.number)

price_value  car_id
0           45100.0       0
2           28000.0       2
3          229500.0       3
4           19500.0       4
5          164900.0       5
...             ...     ...
160609      17900.0  160609
160610      22700.0  160610
160611      15500.0  160611
160614       6490.0  160614
160615      11300.0  160615

[106494 rows x 2 columns]

In [10]:
df.select_dtypes(np.number).columns

Index(['price_value', 'car_id'], dtype='object')

In [0]:
feats = ['car_id']

In [12]:
feats

['car_id']

In [0]:
X = df[feats].values

In [14]:
X

array([[     0],
       [     2],
       [     3],
       ...,
       [160611],
       [160614],
       [160615]])

In [0]:
y = df['price_value'].values

In [16]:
y

array([ 45100.,  28000., 229500., ...,  15500.,   6490.,  11300.])

In [17]:
model = DummyRegressor()
model.fit(X,y)
y_pred = model.predict(X)

mae(y,y_pred)

39465.934630440985

In [18]:
[x for x in df.columns if 'price' in x]

['price_currency', 'price_details', 'price_value']

In [19]:
df['price_currency'].values

array(['PLN', 'PLN', 'PLN', ..., 'PLN', 'PLN', 'PLN'], dtype=object)

In [20]:
df['price_currency'].value_counts()

PLN    106290
EUR       204
Name: price_currency, dtype: int64

In [21]:
df.groupby(by = 'price_currency').size()

price_currency
EUR       204
PLN    106290
dtype: int64

sprawdzanie procent EUR

In [22]:
df['price_currency'].value_counts(normalize=True) * 100

PLN    99.80844
EUR     0.19156
Name: price_currency, dtype: float64

In [23]:
df ['price_currency'] != 'EUR'

0         True
2         True
3         True
4         True
5         True
          ... 
160609    True
160610    True
160611    True
160614    True
160615    True
Name: price_currency, Length: 106494, dtype: bool

In [24]:
df [ df ['price_currency'] != 'EUR']

breadcrumb  ...  car_id
0         [Osobowe, Dacia, Logan, Dacia Logan II (2012-)]  ...       0
2       [Osobowe, Peugeot, 3008, Peugeot 3008 I (2009-...  ...       2
3       [Osobowe, Porsche, Cayenne, Porsche Cayenne II...  ...       3
4       [Osobowe, Peugeot, 308, Peugeot 308 T7 (2008-2...  ...       4
5       [Osobowe, Volkswagen, Golf, Volkswagen Golf VI...  ...       5
...                                                   ...  ...     ...
160609  [Osobowe, Hyundai, i20, Hyundai i20 I (2008-20...  ...  160609
160610                            [Osobowe, Škoda, RAPID]  ...  160610
160611  [Osobowe, Opel, Zafira, Opel Zafira B (2005-20...  ...  160611
160614  [Osobowe, Volkswagen, Passat, Volkswagen Passa...  ...  160614
160615                            [Osobowe, Peugeot, 207]  ...  160615

[106290 rows x 155 columns]

In [0]:
df = df[df ['price_currency'] != 'EUR']

In [26]:
df.shape

(106290, 155)

Features

In [27]:
df.head()

breadcrumb  ... car_id
0    [Osobowe, Dacia, Logan, Dacia Logan II (2012-)]  ...      0
2  [Osobowe, Peugeot, 3008, Peugeot 3008 I (2009-...  ...      2
3  [Osobowe, Porsche, Cayenne, Porsche Cayenne II...  ...      3
4  [Osobowe, Peugeot, 308, Peugeot 308 T7 (2008-2...  ...      4
5  [Osobowe, Volkswagen, Golf, Volkswagen Golf VI...  ...      5

[5 rows x 155 columns]

In [28]:
df ['param_color'].factorize()

(array([-1, -1, -1, ..., -1, -1, -1]),
 Index(['Czarny', 'Srebrny', 'Złoty', 'Bordowy', 'Biały', 'Szary', 'Beżowy',
        'Zielony', 'Fioletowy', 'Niebieski', 'Inny kolor', 'Brązowy', 'Żółty'],
       dtype='object'))

In [29]:
df_fact = pd.DataFrame(df ['param_color'].factorize()[0])
df_fact.sample(5)

0
17139  -1
1845   -1
103831 -1
39565  -1
61322  -1

In [30]:
df

breadcrumb  ...  car_id
0         [Osobowe, Dacia, Logan, Dacia Logan II (2012-)]  ...       0
2       [Osobowe, Peugeot, 3008, Peugeot 3008 I (2009-...  ...       2
3       [Osobowe, Porsche, Cayenne, Porsche Cayenne II...  ...       3
4       [Osobowe, Peugeot, 308, Peugeot 308 T7 (2008-2...  ...       4
5       [Osobowe, Volkswagen, Golf, Volkswagen Golf VI...  ...       5
...                                                   ...  ...     ...
160609  [Osobowe, Hyundai, i20, Hyundai i20 I (2008-20...  ...  160609
160610                            [Osobowe, Škoda, RAPID]  ...  160610
160611  [Osobowe, Opel, Zafira, Opel Zafira B (2005-20...  ...  160611
160614  [Osobowe, Volkswagen, Passat, Volkswagen Passa...  ...  160614
160615                            [Osobowe, Peugeot, 207]  ...  160615

[106290 rows x 155 columns]

In [0]:
SUFFIX_CAT = '__cat'
for feat in df.columns:
  if isinstance(df[feat][0], list): continue
  
  factorized_values = df[feat].factorize()[0]
  if SUFFIX_CAT in feat:
    df[feat] = factorized_values
  else:
    df[feat + SUFFIX_CAT] = factorized_values
  

cat_feats = [x for x in df.columns if SUFFIX_CAT in x]
cat_feats = [x for x in cat_feats if 'price' not in x]

In [32]:
len(cat_feats)

151

In [0]:
X = df[cat_feats].values
y = df['price_value'].values

In [35]:
df.columns

Index(['breadcrumb', 'created_at', 'price_currency', 'price_details',
       'price_value', 'seller_address', 'seller_name', 'seller_type',
       'feature_czujniki-parkowania-przednie',
       'feature_poduszka-powietrzna-chroniąca-kolana',
       ...
       'param_pearl__cat', 'param_stan__cat', 'param_wersja__cat',
       'param_emisja-co2__cat', 'param_body-type__cat', 'param_matowy__cat',
       'param_bezwypadkowy__cat', 'param_akryl-(niemetalizowany)__cat',
       'param_monthly-payment-value__cat', 'car_id__cat'],
      dtype='object', length=309)

In [0]:
model = DecisionTreeRegressor(max_depth=5)
scores = cross_val_score(model, X, y, cv=3, scoring = 'neg_mean_absolute_error')

In [39]:
np.mean(scores)

-19566.588937368328

In [40]:
scores

array([-19625.57510982, -19438.56693715, -19635.62476514])

In [44]:
m = DecisionTreeRegressor(max_depth=5)
m.fit(X,y)

imp = PermutationImportance(m).fit(X,y)
eli5.show_weights(imp, feature_names = cat_feats)